# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo/main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(700, 400))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sbHeight = QtWidgets.QSpinBox(self.groupBox)
        self.sbHeight.setMinimum(10)
        self.sbHeight.setMaximum(1000)
        self.sbHeight.setProperty("value", 100)
        self.sbHeight.setObjectName("sbHeight")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbHeight)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sbWidth = QtWidgets.QSpinBox(self.groupBox)
        self.sbWidth.setMinimum(10)
        self.sbWidth.setMaximum(1000)
        self.sbWidth.setProperty("value", 100)
        self.sbWidth.setObjectName("sbWidth")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbWidth)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sbCoefX = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCoefX.sizePolicy().hasHeightForWidth())
        self.sbCoefX.setSizePolicy(sizePolicy)
        self.sbCoefX.setMinimumSize(QtCore.QSize(60, 0))
        self.sbCoefX.setMinimum(-99.99)
        self.sbCoefX.setSingleStep(0.01)
        self.sbCoefX.setProperty("value", 0.02)
        self.sbCoefX.setObjectName("sbCoefX")
        self.horizontalLayout_2.addWidget(self.sbCoefX)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(15, 0))
        self.label_4.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.sbPowX = QtWidgets.QSpinBox(self.groupBox)
        self.sbPowX.setMinimum(2)
        self.sbPowX.setMaximum(3)
        self.sbPowX.setObjectName("sbPowX")
        self.horizontalLayout_2.addWidget(self.sbPowX)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(10, 0))
        self.label_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.sbCoefC = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCoefC.sizePolicy().hasHeightForWidth())
        self.sbCoefC.setSizePolicy(sizePolicy)
        self.sbCoefC.setMinimumSize(QtCore.QSize(70, 0))
        self.sbCoefC.setMinimum(-9999.0)
        self.sbCoefC.setMaximum(9999.0)
        self.sbCoefC.setSingleStep(10.0)
        self.sbCoefC.setProperty("value", 120.0)
        self.sbCoefC.setObjectName("sbCoefC")
        self.horizontalLayout_2.addWidget(self.sbCoefC)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.sbNumSample = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbNumSample.setMinimum(10)
        self.sbNumSample.setProperty("value", 50)
        self.sbNumSample.setObjectName("sbNumSample")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbNumSample)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.sbFocal = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbFocal.setMinimum(1)
        self.sbFocal.setMaximum(99999)
        self.sbFocal.setSingleStep(10)
        self.sbFocal.setProperty("value", 50)
        self.sbFocal.setObjectName("sbFocal")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sbFocal)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.sbNumVertSamp = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbNumVertSamp.setMinimum(2)
        self.sbNumVertSamp.setMaximum(999)
        self.sbNumVertSamp.setProperty("value", 16)
        self.sbNumVertSamp.setObjectName("sbNumVertSamp")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbNumVertSamp)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.sbNumHorSamp = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbNumHorSamp.setMinimum(2)
        self.sbNumHorSamp.setMaximum(999)
        self.sbNumHorSamp.setProperty("value", 16)
        self.sbNumHorSamp.setObjectName("sbNumHorSamp")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbNumHorSamp)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.btnSolve = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSolve.setObjectName("btnSolve")
        self.verticalLayout.addWidget(self.btnSolve)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.sbGlSampY = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbGlSampY.setMinimum(10)
        self.sbGlSampY.setMaximum(999)
        self.sbGlSampY.setProperty("value", 50)
        self.sbGlSampY.setObjectName("sbGlSampY")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbGlSampY)
        self.sbGlSampX = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbGlSampX.setMinimum(10)
        self.sbGlSampX.setMaximum(999)
        self.sbGlSampX.setProperty("value", 50)
        self.sbGlSampX.setObjectName("sbGlSampX")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbGlSampX)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.glGroundTruth = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.glGroundTruth.sizePolicy().hasHeightForWidth())
        self.glGroundTruth.setSizePolicy(sizePolicy)
        self.glGroundTruth.setObjectName("glGroundTruth")
        self.verticalLayout_3.addWidget(self.glGroundTruth)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplData = QtWidgets.QWidget(self.tab_2)
        self.mplData.setObjectName("mplData")
        self.horizontalLayout.addWidget(self.mplData)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.glResult = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.glResult.sizePolicy().hasHeightForWidth())
        self.glResult.setSizePolicy(sizePolicy)
        self.glResult.setMinimumSize(QtCore.QSize(400, 300))
        self.glResult.setObjectName("glResult")
        self.horizontalLayout_3.addWidget(self.glResult)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "shape-from-template demo"))
        self.groupBox.setTitle(_translate("MainWindow", "Surface"))
        self.label.setText(_translate("MainWindow", "height"))
        self.label_2.setText(_translate("MainWindow", "width"))
        self.label_3.setText(_translate("MainWindow", "formula"))
        self.label_4.setText(_translate("MainWindow", "x^"))
        self.label_5.setText(_translate("MainWindow", "+"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sampling"))
        self.label_7.setText(_translate("MainWindow", "use"))
        self.label_6.setText(_translate("MainWindow", "focal length"))
        self.label_8.setText(_translate("MainWindow", "vert sample"))
        self.label_9.setText(_translate("MainWindow", "horz sample"))
        self.btnSolve.setText(_translate("MainWindow", "Solve"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GL"))
        self.label_10.setText(_translate("MainWindow", "vert sample"))
        self.label_11.setText(_translate("MainWindow", "horz sample"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ground Truth"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Computation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Result"))

